# Generated by Django 3.2.5 on 2021-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', '-'), ('M', 'М'), ('W', 'Ж')], max_length=1, null=True),
        ),
    ]
